### ISSUE TITLE
Number.toLocaleString crashes

### ISSUE THREAD

**Issue by torkelrogstad** [react-community/jsc-android-buildscripts#47] opened 2018-06-26 08:41 UTC
### Issue Description
Calling `Number.toLocaleString` throws an error, `Failed to format a number.`

### Version, config, any additional info
I'm running the `jsc-android-intl` variant of the prebuilt packages. Config file in my React Native are according to the documentation in this repo, except for `android/app/build.gradle`, where I had to use the following config to use the `intl` variant of the provided builds:

```gradle
configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.name == 'android-jsc') {
                details.useTarget group: details.requested.group, name: 'android-jsc-intl', version: 'r224109'
            }
        }
    }
}
```

I found the config information above [here](https://www.ctolib.com/SoftwareMansion-jsc-android-buildscripts.html). Any help greatly appreciated.

Originally I posted about this in #29 but I felt it was more appropriate to have a separate issue.

**Comment by Kmakinator** [comment] 2018-06-26 09:07
This is related to #36. This is problem with loading ICU locale data. I'm currently working on this issue for over a week. I will inform you when I finish

**Comment by DanielZlotin** [comment] 2018-06-26 19:16
closing as duplicate of #36 , will update the README with the missing intl instructions

**Closed by DanielZlotin** 2018-06-26 19:16 UTC

**Comment by deecewan** [comment] 2018-07-10 23:40
@DanielZlotin is this the update you were referring to? https://github.com/react-community/jsc-android-buildscripts/commit/b77d5e18d492ed17e3d9ab9e19f65018e55ff41f#diff-04c6e90faac2675aa89e2176d2eec7d8
